whitelist_rules:
 - closing_brace
 - closure_end_indentation
 - closure_parameter_position
 - closure_spacing
 - colon
 - comma
 - control_statement
 - implicit_getter
 - implicit_return
 - leading_whitespace
 - legacy_constructor
 - legacy_nsgeometry_functions
 - literal_expression_end_indentation
 - mark
 - multiline_parameters
 - multiple_closures_with_trailing_closure
# - opening_brace
 - operator_usage_whitespace
 - operator_whitespace
 - private_over_fileprivate
 - protocol_property_accessors_order
 - redundant_optional_initialization
 - return_arrow_whitespace
 - switch_case_alignment
 - syntactic_sugar
 - trailing_newline
 - trailing_semicolon
 - trailing_whitespace
 - unneeded_break_in_switch
 - unused_enumerated
 - vertical_parameter_alignment
 - vertical_whitespace
 - yoda_condition
# - multiline_arguments
# - unused_closure_parameter
# - strict_fileprivate
# - unneeded_parentheses_in_closure_argument
# - vertical_parameter_alignment_on_call
# - redundant_void_return

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Carthage
  - ThirdPartyFrameworks
